config/routes.rb
Rails.application.routes.draw do  
  
	root "produtos#index"

	# Produtos
	resources :produtos
	post "/produtos/busca" => "produtos#busca", as: :busca_produto

	# Departamentos
	resources :departamentos
end

app/models/departamento.rb
class Departamento < ActiveRecord::Base
	
	validates :nome, presence: true, length: {minimum: 5}
	
end

app/models/produto.rb
class Produto < ActiveRecord::Base

	belongs_to :departamento

	validates :quantidade, presence: true
	validates :nome, presence: true, length: {minimum: 5}
	validates :preco, presence: true
	validates :descricao, presence: true, length: {minimum: 20}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  before_action :set_departamento, only: [:show, :edit, :update, :destroy]

  # GET /departamentos
  # GET /departamentos.json
  def index
    @departamentos = Departamento.all
  end

  # GET /departamentos/1
  # GET /departamentos/1.json
  def show
  end

  # GET /departamentos/new
  def new
    @departamento = Departamento.new
  end

  # GET /departamentos/1/edit
  def edit
  end

  # POST /departamentos
  # POST /departamentos.json
  def create
    @departamento = Departamento.new(departamento_params)

    if @departamento.save
      flash[:success] = "Departamento criado com sucesso!"
      redirect_to departamentos_url
    else
      render :new
    end
  end

  # PATCH/PUT /departamentos/1
  # PATCH/PUT /departamentos/1.json
  def update
    if @departamento.update(departamento_params)
      flash[:success] = "Departamento alterado com sucesso!"
      redirect_to departamentos_url
    else
      render :edit
    end
  end

  # DELETE /departamentos/1
  # DELETE /departamentos/1.json
  def destroy
    @departamento.destroy
    flash[:danger] = "Departamento removido com sucesso!"
    redirect_to departamentos_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departamento
      @departamento = Departamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def departamento_params
      params.require(:departamento).permit(:nome)
    end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
	before_action :set_produto, only: [:show, :edit, :update, :destroy]

	def index
		# O arroba torna a variável acessível na view
		@produtos = Produto.order(:nome).limit(10)
	end

	def new
		@produto = Produto.new
		@departamentos = Departamento.all
	end

	def create
		valores = params.require(:produto).permit(:nome, :preco, :descricao, :quantidade, :departamento_id)
		@produto = Produto.new valores
		if @produto.save
			flash[:success] = "Produto criado com sucesso!"
			redirect_to root_url
		else
			render :new
		end
	end

	def destroy
		id = params["id"]
		Produto.destroy(id)
		flash[:danger] = "Produto removido com sucesso!"
		redirect_to produtos_url
	end

	def busca
		@nomeABuscar = params[:nome]
		@produtos = Produto.where("nome like ?", "%#{@nomeABuscar}%")
	end

	def edit
		@produto = Produto.find(params[:id])
		@departamentos = Departamento.all
		puts "Alguma coisa #{@produto.nome}"
	end

	def update
		if @produto.update(produto_params)
	      flash[:success] = "Produto alterado com sucesso!"
	      redirect_to produtos_url
	    else
	      render :edit
	    end
	end

	private
	    # Use callbacks to share common setup or constraints between actions.
	    def set_produto
	      @produto = Produto.find(params[:id])
	    end

	    # Never trust parameters from the scary internet, only allow the white list through.
	    def produto_params
	      params.require(:produto).permit(:nome, :preco, :descricao, :quantidade, :departamento_id)
	    end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_message
	    messages = ""
	    [:success, :info, :warning, :danger].each {|type|
	      if flash[type]
	        messages += "<div class=\"alert alert-#{type} alert-dismissible\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-hidden=\"true\">×</button><i class=\"icon fa fa-info\"></i> #{flash[type]}</div>"
	      end
	    }
	    messages
 	 end
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/departamentos/_form.html.erb
<%= form_for @departamento do |f| %>
  <div class="box-body">
      <div class="row">
      <div class="col-lg-12">
        <div class="form-group">
          <label>Nome: </label>
          <%= f.text_field :nome, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>
  <div class="box-footer">
    <div class="row pull-right">
      <div class="col-lg-12 ">
        <%= f.submit value: texto_da_acao, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/departamentos/edit.html.erb
<% content_for :pageTitle, "Departamentos - Editar" %>

<% count = 0 %>
<% errorMessage = "<div class=\"alert alert-danger alert-dismissible\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-hidden=\"true\">×</button><i class=\"icon fa fa-info\"></i> Alguma coisa deu errado! Segue a lista de erros abaixo: <br>" %>
<% @departamento.errors.full_messages.each do |message| %>
	<% count = count + 1 %>
	<% errorMessage += "[ERRO#{count}]: #{message} <br>" %>
<% end %>
<% errorMessage += "</div>" %>
<% if count != 0 %>
	<%= errorMessage.html_safe %>
<% end %>

<div class="box">
	<div class="box-header with-border">
		<h3 class="box-title">Editar o departamento</h3>
		<div class="box-tools pull-right">
			<button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse"><i class="fa fa-minus"></i></button>
		</div>
	</div>
	<%= render partial: "form", locals: {texto_da_acao: "Editar Departamento"} %>
</div>

app/views/departamentos/index.html.erb
<% content_for :pageTitle, "Departamentos - Página Inicial" %>
<p id="notice"><%= notice %></p>
<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title">Lista de departamentos</h3>
    <div class="box-title">
      <%= link_to "Novo Departamento", new_departamento_path,
        method: :get, 
        class: "label bg-green" %>
    </div>
    <div class="box-tools pull-right">
      <button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
        <i class="fa fa-minus"></i>
      </button>
    </div>
  </div>
  <div class="box-body">
      <div class="row">
      <div class="col-lg-12">
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th>ID</th>
              <th>Nome</th>
              <th>Ações</th>
            </tr>
          </thead>
          <tbody>
            <% @departamentos.each do |departamento| %>
              <tr>
                <td><%= departamento.id %></td>
                <td><%= departamento.nome %></td>
                <td>
                  <div class="btn-group">
                    <%= button_to "Remover", departamento, 
                      method: "delete", 
                      class: "btn btn-danger btn-xs",
                      data: {confirm: "Tem certeza que deseja remover o departamento: '#{departamento.nome}'?"} %>

                    <%= button_to "Editar", edit_departamento_path(departamento), 
                      method: :get, 
                      class: "btn btn-primary btn-xs" %>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/departamentos/new.html.erb
<% content_for :pageTitle, "Departamentos - Criar" %>

<% count = 0 %>
<% errorMessage = "<div class=\"alert alert-danger alert-dismissible\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-hidden=\"true\">×</button><i class=\"icon fa fa-info\"></i> Alguma coisa deu errado! Segue a lista de erros abaixo: <br>" %>
<% @departamento.errors.full_messages.each do |message| %>
	<% count = count + 1 %>
	<% errorMessage += "[ERRO#{count}]: #{message} <br>" %>
<% end %>
<% errorMessage += "</div>" %>
<% if count != 0 %>
	<%= errorMessage.html_safe %>
<% end %>

<div class="box">
	<div class="box-header with-border">
		<h3 class="box-title">Criar um novo produto</h3>
		<div class="box-tools pull-right">
			<button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse"><i class="fa fa-minus"></i></button>
		</div>
	</div>
	<%= render partial: "form", locals: {texto_da_acao: "Novo Departamento"} %>
</div>

app/views/departamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @departamento.nome %>
</p>

<%= link_to 'Edit', edit_departamento_path(@departamento) %> |
<%= link_to 'Back', departamentos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shirt Store - <%= yield(:pageTitle) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
      	
    	<!-- HEADER -->
      	<header class="main-header">
        	<a href=<%= root_url %> class="logo">
          		<span class="logo-mini"><b>S</b>S</span>
          		<span class="logo-lg"><b>Shirt</b>Store</span>
        	</a>

        	<!-- NAVBAR -->
        	<nav class="navbar navbar-static-top" role="navigation">
		        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
		        	<span class="sr-only">Toggle navigation</span>
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
		        </a>
		        <div class="navbar-custom-menu">
		            <ul class="nav navbar-nav">
		              <li>
		                <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
		              </li>
		            </ul>
		        </div>
        	</nav>
      	</header>

     	<!-- =============================================== -->

     	<!-- SIDEBAR -->
     	<aside class="main-sidebar">
	        <section class="sidebar">

	        	<!-- SEARCH FORM -->
	          	<%= form_tag busca_produto_path, method: :post, class: "sidebar-form" do %>
	          		<div class="input-group">
	          			<%= text_field_tag :nome, @nomeABuscar, class: "form-control", placeholder: "Search..." %>
	          			<span class="input-group-btn">
	          				<%= button_to nil, class: "btn btn-flat" do %>
								<i class="fa fa-search"></i>
	          				<% end %>
	          			</span>
	          		</div>
	          	<% end %>

				<!-- SIDEBAR MENU -->
	         	<ul class="sidebar-menu">
	            	<li class="header">MAIN NAVIGATION</li>
	            	<li class=<%= current_page?(root_url) ? "active" : nil %>>
	              		<a href=<%= root_url %>
	                		<i class="fa fa-dashboard"></i> <span>Dashboard</span>
	        			</a>
	            	</li>
	            	<li class=<%= current_page?(produtos_path) ? "active" : current_page?(new_produto_path) ? "active" : nil %> >
	              		<a href="#">
	                		<i class="fa fa-files-o"></i>
	                		<span>Produtos</span>
	                		<i class="fa fa-angle-left pull-right"></i>
	              		</a>
	              		<ul class="treeview-menu">
	                		<li class=<%= current_page?(produtos_path) ? "active" : nil %> >
	                			<%= link_to "<i class=\"fa fa-circle-o\"></i> Lista de Produtos".html_safe , produtos_path %>
	            			</li>
	                		<li class=<%= current_page?(new_produto_path) ? "active" : nil %>>
	                			<%= link_to "<i class=\"fa fa-circle-o\"></i> Novo Produto".html_safe , new_produto_path %>
	            			</li>
	              		</ul>
	            	</li>
                <li class=<%= current_page?(departamentos_path) ? "active" : current_page?(new_departamento_path) ? "active" : nil %> >
                    <a href="#">
                      <i class="fa fa-tags"></i>
                      <span>Departamentos</span>
                      <i class="fa fa-angle-left pull-right"></i>
                    </a>
                    <ul class="treeview-menu">
                      <li class=<%= current_page?(departamentos_path) ? "active" : nil %> >
                        <%= link_to "<i class=\"fa fa-circle-o\"></i> Lista de Departamentos".html_safe , departamentos_path %>
                    </li>
                      <li class=<%= current_page?(new_departamento_path) ? "active" : nil %>>
                        <%= link_to "<i class=\"fa fa-circle-o\"></i> Novo Departamento".html_safe , new_departamento_path %>
                    </li>
                    </ul>
                </li>
	          	</ul>
	        </section>
      	</aside>

      <!-- =============================================== -->

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            <%= yield(:pageTitle) %>
            <small><%= yield(:pageSubtitle) %></small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Examples</a></li>
            <li class="active">Blank page</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
        	<%= flash_message.html_safe  %>
        	<%= yield %>
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->

      <footer class="main-footer">
        <strong>Copyright 2016 <a href="http://codinglab.com.br">CodingLab</a>.</strong> All rights reserved.
      </footer>

      <!-- Control Sidebar -->
      <aside class="control-sidebar control-sidebar-dark">
        <!-- Create the tabs -->
        <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
          <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>

          <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
          <!-- Home tab content -->
          <div class="tab-pane" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class="control-sidebar-menu">
              <li>
                <a href="javascript::;">
                  <i class="menu-icon fa fa-birthday-cake bg-red"></i>
                  <div class="menu-info">
                    <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>
                    <p>Will be 23 on April 24th</p>
                  </div>
                </a>
              </li>
              <li>
                <a href="javascript::;">
                  <i class="menu-icon fa fa-user bg-yellow"></i>
                  <div class="menu-info">
                    <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>
                    <p>New phone +1(800)555-1234</p>
                  </div>
                </a>
              </li>
              <li>
                <a href="javascript::;">
                  <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>
                  <div class="menu-info">
                    <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>
                    <p>nora@example.com</p>
                  </div>
                </a>
              </li>
              <li>
                <a href="javascript::;">
                  <i class="menu-icon fa fa-file-code-o bg-green"></i>
                  <div class="menu-info">
                    <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>
                    <p>Execution time 5 seconds</p>
                  </div>
                </a>
              </li>
            </ul><!-- /.control-sidebar-menu -->

            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class="control-sidebar-menu">
              <li>
                <a href="javascript::;">
                  <h4 class="control-sidebar-subheading">
                    Custom Template Design
                    <span class="label label-danger pull-right">70%</span>
                  </h4>
                  <div class="progress progress-xxs">
                    <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                  </div>
                </a>
              </li>
              <li>
                <a href="javascript::;">
                  <h4 class="control-sidebar-subheading">
                    Update Resume
                    <span class="label label-success pull-right">95%</span>
                  </h4>
                  <div class="progress progress-xxs">
                    <div class="progress-bar progress-bar-success" style="width: 95%"></div>
                  </div>
                </a>
              </li>
              <li>
                <a href="javascript::;">
                  <h4 class="control-sidebar-subheading">
                    Laravel Integration
                    <span class="label label-warning pull-right">50%</span>
                  </h4>
                  <div class="progress progress-xxs">
                    <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
                  </div>
                </a>
              </li>
              <li>
                <a href="javascript::;">
                  <h4 class="control-sidebar-subheading">
                    Back End Framework
                    <span class="label label-primary pull-right">68%</span>
                  </h4>
                  <div class="progress progress-xxs">
                    <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
                  </div>
                </a>
              </li>
            </ul><!-- /.control-sidebar-menu -->

          </div><!-- /.tab-pane -->
          <!-- Stats tab content -->
          <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div><!-- /.tab-pane -->
          <!-- Settings tab content -->
          <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
              <h3 class="control-sidebar-heading">General Settings</h3>
              <div class="form-group">
                <label class="control-sidebar-subheading">
                  Report panel usage
                  <input type="checkbox" class="pull-right" checked>
                </label>
                <p>
                  Some information about this general settings option
                </p>
              </div><!-- /.form-group -->

              <div class="form-group">
                <label class="control-sidebar-subheading">
                  Allow mail redirect
                  <input type="checkbox" class="pull-right" checked>
                </label>
                <p>
                  Other sets of options are available
                </p>
              </div><!-- /.form-group -->

              <div class="form-group">
                <label class="control-sidebar-subheading">
                  Expose author name in posts
                  <input type="checkbox" class="pull-right" checked>
                </label>
                <p>
                  Allow the user to show his name in blog posts
                </p>
              </div><!-- /.form-group -->

              <h3 class="control-sidebar-heading">Chat Settings</h3>

              <div class="form-group">
                <label class="control-sidebar-subheading">
                  Show me as online
                  <input type="checkbox" class="pull-right" checked>
                </label>
              </div><!-- /.form-group -->

              <div class="form-group">
                <label class="control-sidebar-subheading">
                  Turn off notifications
                  <input type="checkbox" class="pull-right">
                </label>
              </div><!-- /.form-group -->

              <div class="form-group">
                <label class="control-sidebar-subheading">
                  Delete chat history
                  <a href="javascript::;" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
                </label>
              </div><!-- /.form-group -->
            </form>
          </div><!-- /.tab-pane -->
        </div>
      </aside><!-- /.control-sidebar -->
      <!-- Add the sidebar's background. This div must be placed
           immediately after the control sidebar -->
      <div class="control-sidebar-bg"></div>
    </div><!-- ./wrapper -->
  </body>
</html>

app/views/produtos/_form.html.erb
<%= form_for @produto do |f| %>
  <div class="box-body">
      <div class="row">
      <div class="col-lg-12">
          <div class="row">
            <div class="col-lg-6">
              <div class="form-group">
                <label>Nome: </label>
                <%= f.text_field :nome, class: "form-control" %>
              </div>
            </div>
            <div class="col-lg-2">
              <div class="form-group">
                <label>Quantidade: </label>
                <%= f.number_field :quantidade, step: 1, min: 1, class: "form-control" %>
              </div>
            </div>
            <div class="col-lg-2">
              <label>Preço: </label>
              <%= f.number_field :preco, class: "form-control" %>
            </div>
            <div class="col-lg-2">
              <label>Departamento: </label>
              <%= f.collection_select :departamento_id, @departamentos, :id, :nome, {}, class: "form-control" %>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-12">
              <label>Descrição: </label>
              <%= f.text_area :descricao, rows: 4, class: "form-control" %>
            </div>
          </div>
      </div>
    </div>
  </div>
  <div class="box-footer">
    <div class="row pull-right">
      <div class="col-lg-12 ">
        <%= f.submit value: texto_da_acao, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/produtos/_produto.html.erb
<!-- Arquivo nomeado com _ para identificar um partial -->
<tr>
	<td><%= produto.id %></td>
	<td><%= produto.nome %></td>
	<td><%= produto.descricao %></td>
	<td><%= produto.preco %></td>
	<td><%= produto.quantidade %></td>
	<td><%= produto.departamento.nome %></td>
	<td>
		<div class="btn-group">
			<%= button_to "Remover", produto, 
				method: "delete", 
				class: "btn btn-danger btn-xs",
				data: {confirm: "Tem certeza que deseja remover o produto: '#{produto.nome}'?"} %>

			<%= button_to "Editar", edit_produto_path(produto), 
				method: :get, 
				class: "btn btn-primary btn-xs" %>
		</div>
	</td>
</tr>

app/views/produtos/busca.html.erb
<% content_for :pageTitle, "Busca de produtos" %>
<div class="box">
	<div class="box-header with-border">
		<h3 class="box-title">Lista de produtos retornados na busca</h3>
		<div class="box-tools pull-right">
			<button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
				<i class="fa fa-minus"></i>
			</button>
		</div>
	</div>
	<div class="box-body">
	  	<div class="row">
			<div class="col-lg-12">
				<table class="table table-striped table-hover">
					<thead>
						<tr>
							<th>ID</th>
							<th>Nome</th>
							<th>Descrição</th>
							<th>Preço</th>
							<th>Quantidade</th>
							<th>Ações</th>
						</tr>
					</thead>
					<tbody>
						<%= render partial: "produto", collection: @produtos %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

app/views/produtos/create.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<h1>Criado!</h1>
</body>
</html>

app/views/produtos/edit.html.erb
<% content_for :pageTitle, "Departamentos - Editar" %>

<% count = 0 %>
<% errorMessage = "<div class=\"alert alert-danger alert-dismissible\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-hidden=\"true\">×</button><i class=\"icon fa fa-info\"></i> Alguma coisa deu errado! Segue a lista de erros abaixo: <br>" %>
<% @produto.errors.full_messages.each do |message| %>
	<% count = count + 1 %>
	<% errorMessage += "[ERRO#{count}]: #{message} <br>" %>
<% end %>
<% errorMessage += "</div>" %>
<% if count != 0 %>
	<%= errorMessage.html_safe %>
<% end %>

<div class="box">
	<div class="box-header with-border">
		<h3 class="box-title">Editar o produto</h3>
		<div class="box-tools pull-right">
			<button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse"><i class="fa fa-minus"></i></button>
		</div>
	</div>
	<%= render partial: "form", locals: {texto_da_acao: "Editar Produto"} %>
</div>

app/views/produtos/index.html.erb
<% content_for :pageTitle, "Página Inicial" %>
<div class="box">
	<div class="box-header with-border">
		<h3 class="box-title">Lista de produtos </h3>
		<div class="box-title">
			<%= link_to "Novo Produto", new_produto_path,
				method: :get, 
				class: "label bg-green" %>
		</div>
		<div class="box-tools pull-right">
			<button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
				<i class="fa fa-minus"></i>
			</button>
		</div>
	</div>
	<div class="box-body">
	  	<div class="row">
			<div class="col-lg-12">
				<table class="table table-striped table-hover">
					<thead>
						<tr>
							<th>ID</th>
							<th>Nome</th>
							<th>Descrição</th>
							<th>Preço</th>
							<th>Quantidade</th>
							<th>Departamento</th>
							<th>Ações</th>
						</tr>
					</thead>
					<tbody>
						<%= render partial: "produto", collection: @produtos %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

app/views/produtos/new.html.erb
<% content_for :pageTitle, "Produtos - Criar" %>

<% count = 0 %>
<% errorMessage = "<div class=\"alert alert-danger alert-dismissible\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-hidden=\"true\">×</button><i class=\"icon fa fa-info\"></i> Alguma coisa deu errado! Segue a lista de erros abaixo: <br>" %>
<% @produto.errors.full_messages.each do |message| %>
	<% count = count + 1 %>
	<% errorMessage += "[ERRO#{count}]: #{message} <br>" %>
<% end %>
<% errorMessage += "</div>" %>
<% if count != 0 %>
	<%= errorMessage.html_safe %>
<% end %>

<div class="box">
	<div class="box-header with-border">
		<h3 class="box-title">Criar um novo produto</h3>
		<div class="box-tools pull-right">
			<button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse"><i class="fa fa-minus"></i></button>
		</div>
	</div>
	<%= render partial: "form", locals: {texto_da_acao: "Novo Produto"} %>
</div>